/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.login;

import DomainModel.TaiKhoan;
import DomainModel.Users;
import Repository.TaiKhoanRepository;
import Repository.UserRepositoty;
import Service.Impl.TaiKhoanImpl;
import Service.Impl.UsersImpl;
import Services.TaiKhoanService;
import Services.UsersService;
import View.TrangChu.TrangChu;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class formdangnhap extends javax.swing.JPanel {

    TaiKhoanService taikhoanservice = new TaiKhoanImpl();
    UsersService userservice = new UsersImpl();
    List<TaiKhoan> ListTaiKhoan = new ArrayList<>();
    List<Users> ListUsers = new ArrayList<>();
 
    
    public formdangnhap() {
        initComponents();
        txt_users.grabFocus();
    }
    public void backLogin() {
       txt_users.grabFocus();
    }
    public boolean login() {
        String userName = txt_users.getText();
        String passWord = new String(txt_word.getPassword());
        try {          
            TaiKhoan taikhoan = taikhoanservice.gettaikhoan(userName);
            if (taikhoan == null) {    //nếu user sai
                JOptionPane.showMessageDialog(this,"Sai Ten Dang Nhap");
                return false;
            } else {
                String  passwordSystem = taikhoan.getMatKhau();
                if (passWord.equalsIgnoreCase(passwordSystem)) {
                    JOptionPane.showMessageDialog(this,"Dang Nhap Thanh Cong");
                    Users users=  userservice.getUsers(taikhoan.getIdUser());
                    System.out.println(taikhoan.getIdUser());
                    Auth.user = users;
                    new TrangChu().setVisible(true);
                    this.setVisible(false);
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this,"sai mat khau");
                    return false;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"loi truy van du lieu");
        }
        return true;

    }
public void addEventRegister(ActionListener event) {
        btn_quen.addActionListener(event);
    }
public void addEventLogin(ActionListener event) {
        btn_dangNhap.addActionListener(event);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_users = new View.login.txtField();
        txt_word = new View.login.password();
        btn_dangNhap = new View.login.button();
        btn_quen = new View.login.button();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txt_users.setText("admin");
        txt_users.setHint("USERSNAME");

        txt_word.setText("123456");
        txt_word.setHint("PASSWORD");
        txt_word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_wordActionPerformed(evt);
            }
        });

        btn_dangNhap.setBackground(new java.awt.Color(104, 159, 158));
        btn_dangNhap.setText("Đăng Nhập");
        btn_dangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });

        btn_quen.setBackground(new java.awt.Color(255, 255, 255));
        btn_quen.setText("Quên Mật Khẩu");
        btn_quen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng Nhập");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_word, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_users, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_dangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_quen, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(txt_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txt_word, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btn_dangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_quen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_wordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_wordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_wordActionPerformed

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_btn_dangNhapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.login.button btn_dangNhap;
    private View.login.button btn_quen;
    private javax.swing.JLabel jLabel1;
    private View.login.txtField txt_users;
    private View.login.password txt_word;
    // End of variables declaration//GEN-END:variables

    
}
